openapi: 3.0.0
info:
  title: sistema-cancer
  description: Api Web
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: "Local server"
  - url: https://secure-brushlands-86892.herokuapp.com
    description: "Production server"
tags:
  - name: common
    description: Common routes
  - name: user
    description: User routes
paths:
  #USER
  /v1/users/create-one:
    post:
      tags:
        - user
      summary: create a user
      description: http://localhost:3000/v1/users/create-one
      operationId: user:create-one
      requestBody: 
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user-create-one"
      responses:
        "201":
          description: user created correctly
          content:
            application/json:
              schema:
                $ref: "#/components/responses/response"
  /v1/users/{id}/delete-one:
    delete:
      tags:
        - user
      summary: delete one user
      description: http://localhost:3000/v1/users/{id}/delete-one
      operationId: user:delete-one
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: number
            example: 1
          description: The id of the user to delete
      responses:
        "204":
          description: satisfactory removal
        "404":
          description: Not found user with provided id
          content:
            application/json:
              schema:
                $ref: "#/components/responses/404_not_found"
  /v1/users/{id}/update-one:
    put:
      tags:
        - user
      summary: update one user
      description: http://localhost:3000/v1/users/{id}/update-one
      operationId: user:update-one
      requestBody: 
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user-create-one"
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: number
            example: 1
          description: The id of the user to update
      responses:
        "200":
          description: user updated
          content:
            application/json:
              schema:
                $ref: "#/components/responses/response"
        "404":
          description: Not found user with provided id
          content:
            application/json:
              schema:
                $ref: "#/components/responses/404_not_found"
  #COMMON
  /:
    get:
      tags:
        - common
      summary: ''
      description: ''
      operationId: common:get
      responses:
        "200":
          description: Service OK 游놓
  /healthy:
    get:
      tags:
        - common
      summary: ''
      description: ''
      operationId: common:healthy
      responses:
        "200":
          description: Service OK 游놓
  /readiness:
    get:
      tags:
        - common
      summary: ''
      description: ''
      operationId: common:readiness
      responses:
        "200":
          description: Service OK 游놓
components: 
  schemas:
    user-create-one:
      title: user-create-one
      type: object
      properties:
        nombre: 
          type: string
          example: Alejandro
        email:
          type: string
          example: alejandro@gmail.com
        contrase침a:
          type: string
          example: contrase침a123
        es_admin:
          type: boolean
          example: false
  #RESPONSES
    api_response:
      title: ApiResponse
      required:
        - result
        - status
      type: object
      properties:
        result:
          type: object
          description: Object according to the requested resource
        status:
          type: integer
          description: HTTP code status
          example: 200
    api_error:
      title: ApiError
      required:
        - message
        - code
      type: object
      properties:
        message:
          type: string
          description: Message that describes the error
        code:
          type: integer
          description: Code of error
        metadata:
          type: object
          description: More info of error
    list_reponse:
      title: ListResponse
      required:
        - items
        - total
      type: object
      properties:
        items:
          type: array
          items:
            type: object
          description: response elements according to the resource
        total:
          type: integer
          description: total of items saved
    api_list_reponse:
      title: ApiListResponse
      required:
        - result
        - status
      type: object
      properties:
        result:
          $ref: "#/components/schemas/list_reponse"
        status:
          type: integer
          description: HTTP code status
  responses:
    response:
      $ref: "#/components/schemas/api_response"
    list_response:
      $ref: "#/components/schemas/api_list_reponse"
    error:
      $ref: "#/components/schemas/api_error"
    404_not_found:
      $ref: "#/components/schemas/api_error"

