openapi: 3.0.0
info:
  title: sistema-depresion
  description: Api Web
  version: 1.0.3
servers:
  - url: http://localhost:3000
    description: "Local server"
  - url: https://secure-brushlands-86892.herokuapp.com
    description: "Production server"
tags:
  - name: common
    description: Common routes
  - name: user
    description: User routes
  - name: question
    description: Question routes
paths:
  #USER
  /v1/users/create-one:
    post:
      tags:
        - user
      summary: create a user
      description: http://localhost:3000/v1/users/create-one
      operationId: user:create-one
      security:
        - BearerAuth: []
      requestBody: 
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user-create-one"
      responses:
        "201":
          description: user created correctly
          content:
            application/json:
              schema:
                $ref: "#/components/responses/response"
        "401":
          description: Access token doesn't have the required permission
          content:
            application/json:
              schema:
                $ref: "#/components/responses/error"
        "403":
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/responses/error"
  /v1/users/{id}/delete-one:
    delete:
      tags:
        - user
      summary: delete one user
      description: http://localhost:3000/v1/users/{id}/delete-one
      operationId: user:delete-one
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: number
            example: 1
          description: The id of the user to delete
      responses:
        "204":
          description: satisfactory removal
        "404":
          description: Not found user with provided id
          content:
            application/json:
              schema:
                $ref: "#/components/responses/404_not_found"
        "401":
          description: Access token doesn't have the required permission
          content:
            application/json:
              schema:
                $ref: "#/components/responses/error"
        "403":
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/responses/error"
  /v1/users/{email}/update-one:
    put:
      tags:
        - user
      summary: update one user
      description: http://localhost:3000/v1/users/{email}/update-one
      operationId: user:update-one
      requestBody: 
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user-update-one"
      parameters:
        - name: email
          in: path
          required: true
          style: simple
          schema:
            type: string
            example: alejandro@gmail.com
          description: The email of the user to update
      responses:
        "200":
          description: user updated
          content:
            application/json:
              schema:
                $ref: "#/components/responses/response"
        "404":
          description: Not found user with provided email
          content:
            application/json:
              schema:
                $ref: "#/components/responses/404_not_found"
  /v1/users/get-all:
    get:
      tags:
        - user
      summary: Get all users
      description: http://localhost:3000/v1/users/get-all
      operationId: user:get-all
      parameters:
        - in: query
          name: email
          required: false
          schema:
            type: string
            example: alejandro@gmail.com
        - in: query
          name: es_admin
          required: false
          schema: 
            type: boolean
            example: false
      security:
        - BearerAuth: []
      responses:
        200:
          description: get all users
          content:
            application/json:
              schema:
                $ref: "#/components/responses/list_response"
        "401":
          description: Access token doesn't have the required permission
          content:
            application/json:
              schema:
                $ref: "#/components/responses/error"
        "403":
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/responses/error"
  /v1/users/login:
    post:
      tags:
        - user
      summary: login user
      description: http://localhost:3000/v1/users/login
      operationId: user:login
      requestBody: 
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user-login"
      responses:
        200:
          description: correct login
          content:
            application/json:
              schema:
                $ref: "#/components/responses/list_response"
  
  #QUESTIONS
  /v1/questions/create-one:
    post:
      tags:
        - question
      summary: create a question
      description: http://localhost:3000/v1/questions/create-one
      operationId: question:create-one
      security:
        - BearerAuth: []
      requestBody: 
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/question-create-one"
      responses:
        "201":
          description: question created correctly
          content:
            application/json:
              schema:
                $ref: "#/components/responses/response"
        "401":
          description: Access token doesn't have the required permission
          content:
            application/json:
              schema:
                $ref: "#/components/responses/error"
        "403":
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/responses/error"
  /v1/questions/get-all:
    get:
      tags:
        - question
      summary: Get all questions
      description: http://localhost:3000/v1/questions/get-all
      operationId: question:get-all
      parameters:
        - in: query
          name: id
          required: false
          schema:
            type: number
            example: 1
        - in: query
          name: pregunta
          required: false
          schema:
            type: string
            example: ¿Presenta pérdida de interés por realizar actividades?
      security:
        - BearerAuth: []
      responses:
        200:
          description: get all questions
          content:
            application/json:
              schema:
                $ref: "#/components/responses/list_response"
        "401":
          description: Access token doesn't have the required permission
          content:
            application/json:
              schema:
                $ref: "#/components/responses/error"
        "403":
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/responses/error"
  /v1/questions/{id}/delete-one:
    delete:
      tags:
        - question
      summary: delete one question
      description: http://localhost:3000/v1/questions/{id}/delete-one
      operationId: question:delete-one
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: number
            example: 1
          description: The id of the question to delete
      responses:
        "204":
          description: satisfactory removal
        "404":
          description: Not found question with provided id
          content:
            application/json:
              schema:
                $ref: "#/components/responses/404_not_found"
        "401":
          description: Access token doesn't have the required permission
          content:
            application/json:
              schema:
                $ref: "#/components/responses/error"
        "403":
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/responses/error"
  /v1/questions/{id}/update-one:
    put:
      tags:
        - question
      summary: update one question
      description: http://localhost:3000/v1/questions/{id}/update-one
      operationId: question:update-one
      requestBody: 
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/question-update-one"
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: number
            example: 1
          description: The id of the user to update
      responses:
        "200":
          description: question updated
          content:
            application/json:
              schema:
                $ref: "#/components/responses/response"
        "404":
          description: Not found question with provided id
          content:
            application/json:
              schema:
                $ref: "#/components/responses/404_not_found"
        "401":
          description: Access token doesn't have the required permission
          content:
            application/json:
              schema:
                $ref: "#/components/responses/error"
        "403":
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: "#/components/responses/error"
  #COMMON
  /:
    get:
      tags:
        - common
      summary: ''
      description: ''
      operationId: common:get
      responses:
        "200":
          description: Service OK 👽
  /healthy:
    get:
      tags:
        - common
      summary: ''
      description: ''
      operationId: common:healthy
      responses:
        "200":
          description: Service OK 👽
  /readiness:
    get:
      tags:
        - common
      summary: ''
      description: ''
      operationId: common:readiness
      responses:
        "200":
          description: Service OK 👽
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    #USERS
    user-create-one:
      title: user-create-one
      type: object
      properties:
        cedula:
          type: string
          example: '1233912554'
        nombre: 
          type: string
          example: Alejandro
        email:
          type: string
          example: alejandro@gmail.com
        es_admin:
          type: boolean
          example: false
    user-update-one:
      title: user-update-one
      type: object
      properties:
        cedula:
          type: string
          example: '1233912554'
        nombre: 
          type: string
          example: Alejandro
        email:
          type: string
          example: alejandro@gmail.com
        es_admin:
          type: boolean
          example: false
        contraseña:
          type: string
          example: hola123
    user-login:
      title: user-login
      type: object
      properties:
        email:
          type: string
          example: alejandro@gmail.com
        contraseña:
          type: string
          example: contraseña123
  #QUESTIONS
    question-create-one:
      title: question-create-one
      type: object
      properties:
        pregunta:
          type: string
          example: ¿Presenta pérdida de interés por realizar actividades?
        sintomas:
          type: array
          items:
            type: integer
    question-update-one:
      title: question-update-one
      type: object
      properties:
        pregunta:
          type: string
          example: ¿Presenta pérdida de interés por realizar actividades?
  #RESPONSES
    api_response:
      title: ApiResponse
      required:
        - result
        - status
      type: object
      properties:
        result:
          type: object
          description: Object according to the requested resource
        status:
          type: integer
          description: HTTP code status
          example: 200
    api_error:
      title: ApiError
      required:
        - message
        - code
      type: object
      properties:
        message:
          type: string
          description: Message that describes the error
        code:
          type: integer
          description: Code of error
        metadata:
          type: object
          description: More info of error
    list_reponse:
      title: ListResponse
      required:
        - items
        - total
      type: object
      properties:
        items:
          type: array
          items:
            type: object
          description: response elements according to the resource
        total:
          type: integer
          description: total of items saved
    api_list_reponse:
      title: ApiListResponse
      required:
        - result
        - status
      type: object
      properties:
        result:
          $ref: "#/components/schemas/list_reponse"
        status:
          type: integer
          description: HTTP code status
  responses:
    response:
      $ref: "#/components/schemas/api_response"
    list_response:
      $ref: "#/components/schemas/api_list_reponse"
    error:
      $ref: "#/components/schemas/api_error"
    404_not_found:
      $ref: "#/components/schemas/api_error"

